// Code generated by "stringer -type ErrorCode"; DO NOT EDIT.

package apperrors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BadRequest-0]
	_ = x[Unauthorized-1]
	_ = x[Forbidden-2]
	_ = x[NotFound-3]
	_ = x[InternalServerError-4]
	_ = x[BadGateway-5]
	_ = x[ServiceUnavailable-6]
	_ = x[GatewayTimeout-7]
	_ = x[DatabaseError-8]
	_ = x[NullReferenceError-9]
	_ = x[SQLConnectionError-10]
	_ = x[SQLQueryError-11]
	_ = x[SQLNoRowsError-12]
}

const _ErrorCode_name = "BadRequestUnauthorizedForbiddenNotFoundInternalServerErrorBadGatewayServiceUnavailableGatewayTimeoutDatabaseErrorNullReferenceErrorSQLConnectionErrorSQLQueryErrorSQLNoRowsError"

var _ErrorCode_index = [...]uint8{0, 10, 22, 31, 39, 58, 68, 86, 100, 113, 131, 149, 162, 176}

func (i ErrorCode) String() string {
	if i < 0 || i >= ErrorCode(len(_ErrorCode_index)-1) {
		return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorCode_name[_ErrorCode_index[i]:_ErrorCode_index[i+1]]
}